/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 clock.gltf 
Author: Lyskilde (https://sketchfab.com/longtail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grandfather-clock-cef39f1bd3df43578236f273f273a873
Title: Grandfather Clock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/clock/clock.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ClockCase_ClockCase_0.geometry} material={materials.ClockCase} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Clockface_Clockface_0.geometry} material={materials.Clockface} position={[16.479, 176.538, 0.006]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} position={[18.399, 146.384, 0.006]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MoonDial_MoonDial_0.geometry} material={materials.MoonDial} position={[16.42, 198.777, 0.006]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/clock.gltf')
