/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Wevensson (https://sketchfab.com/Wevensson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grandfather-clock-5dfff9d9c87f44cba61fb83179b0e3e2
Title: Grandfather Clock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PillarD_L1_lambert1_0.geometry} material={materials.lambert1} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
